name: Delete old workflow runs and Run Tests
on:
  schedule:
    - cron: '* * * * *' # Run every minute
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        # Add steps to set up your project's environment
        # For example, installing dependencies

      - name: Run tests
        # Add your test command here
        run: |
          # Replace this with your actual test command
          echo "Running tests..."
          # Example: npm test
